import { ThemeProvider } from "@/components/ui/ThemeInitializer";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import ReduxProvider from "../lib/Providers";
import "./globals.css";

const getInter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${getInter.variable} antialiased`}>
        <ReduxProvider>
          <ThemeProvider>{children}</ThemeProvider>
        </ReduxProvider>
      </body>
    </html>
  );
}
